metalnews3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),# Django JET URLS
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('news.urls', namespace='news'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('', MainPage.as_view(), name='post_list'),
    path('<str:slug>/', post_detail, name='post_detail'),
    path('album/<str:slug>/', AlbumDetailView.as_view(), name='album_detail'),
    path('album/review/<str:slug>/', AddReview.as_view(), name='add_review'),
    path('comment/<str:slug>/', AddComment.as_view(), name='add_comment'),
    path('category/<str:category_name>', CategoryListView.as_view(), name='category_post_list'),
    path('post/<int:pk>/like/',
         login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
         name='post_like'),
    path('post/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)),
         name='post_dislike'),
    path('comment/<int:pk>/like/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
         name='comment_like'),
    path('comment/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
         name='comment_dislike'),
    path('album/<int:pk>/like/',
         login_required(VotesView.as_view(model=Album, vote_type=LikeDislike.LIKE)),
         name='album_like'),
    path('album/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Album, vote_type=LikeDislike.DISLIKE)),
         name='album_dislike'),
]

templates/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="./index.html">Homepage</a></li>
                        <li><a href="./categories.html">Categories</a></li>
                        <li><a href="./blog.html">Our Blog</a></li>
                        <li><a href="#">Contacts</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'news:post_list' %}">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="{% url 'news:post_list' %}">Главная</a></li>
                            <li><a href="./categories.html">Categories <span class="arrow_carrot-down"></span></a>
                                <ul class="dropdown">
                                    <li><a href="./categories.html">Categories</a></li>
                                    <li><a href="./anime-details.html">Anime Details</a></li>
                                    <li><a href="./anime-watching.html">Anime Watching</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                    <li><a href="./signup.html">Sign Up</a></li>
                                    <li><a href="./login.html">Login</a></li>
                                </ul>
                            </li>
                            <li><a href="./blog.html">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    <a href="./login.html"><span class="icon_profile"></span></a>
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->

templates/includes/sidebar.html
{% load static %}
<div class="col-lg-4 col-md-6 col-sm-8">
    <div class="product__sidebar">
        <div class="product__sidebar__view">
            <div class="section-title">
                <h5>Лучшее за:</h5>
            </div>
            <ul class="filter__controls">
                <li class="active" data-filter=".day">День</li>
                <li data-filter=".week">Неделю</li>
                <li data-filter=".month">Месяц</li>
                <li data-filter=".years">Все время</li>

            </ul>

            <div class="filter__gallery">
                {% for pop_post in popular_day %}
                    <div class="product__sidebar__view__item set-bg mix day"
                         data-setbg="{{ pop_post.image.url }}">
                        <div class="ep">{% if pop_post.votes.sum_rating < 0 %}<i class="fas fa-poop ">{% else %}
                            <i class="fas fa-fire-alt">{% endif %}</i> {{ pop_post.votes.sum_rating }}</div>
                        <div class="view"><i class="fa fa-eye"></i> {{ pop_post.views }}</div>
                        <h5><a href="{{ pop_post.get_absolute_url }}">{{ pop_post.title }}</a></h5>
                    </div>
                {% endfor %}
                {% for pop_post in popular_week %}
                    <div class="product__sidebar__view__item set-bg mix week"
                         data-setbg="{{ pop_post.image.url }}">
                        <div class="ep">{% if pop_post.votes.sum_rating < 0 %}<i class="fas fa-poop ">{% else %}
                            <i class="fas fa-fire-alt">{% endif %}</i> {{ pop_post.votes.sum_rating }}</div>
                        <div class="view"><i class="fa fa-eye"></i> {{ pop_post.views }}</div>
                        <h5><a href="{{ pop_post.get_absolute_url }}">{{ pop_post.title }}</a></h5>
                    </div>
                {% endfor %}
                {% for pop_post in popular_month %}
                    <div class="product__sidebar__view__item set-bg mix month"
                         data-setbg="{{ pop_post.image.url }}">
                        <div class="ep">{% if pop_post.votes.sum_rating < 0 %}<i class="fas fa-poop ">{% else %}
                            <i class="fas fa-fire-alt">{% endif %}</i> {{ pop_post.votes.sum_rating }}</div>
                        <div class="view"><i class="fa fa-eye"></i> {{ pop_post.views }}</div>
                        <h5><a href="{{ pop_post.get_absolute_url }}">{{ pop_post.title }}</a></h5>
                    </div>
                {% endfor %}
                {% for pop_post in popular_years %}
                    <div class="product__sidebar__view__item set-bg mix years"
                         data-setbg="{{ pop_post.image.url }}">
                        <div class="ep">{% if pop_post.votes.sum_rating < 0 %}<i class="fas fa-poop ">{% else %}
                            <i class="fas fa-fire-alt">{% endif %}</i> {{ pop_post.votes.sum_rating }}</div>
                        <div class="view"><i class="fa fa-eye"></i> {{ pop_post.views }}</div>
                        <h5><a href="{{ pop_post.get_absolute_url }}">{{ pop_post.title }}</a></h5>
                    </div>
                {% endfor %}

            </div>
        </div>
        <div class="product__sidebar__comment">
            <div class="section-title">
                <h5>Новые комментарии</h5>
            </div>
            {% for comment in comments %}
                <div class="product__sidebar__comment__item">
                    <div class="product__sidebar__comment__item__pic">
                        <img src="{{ comment.post.image.url }}" alt="">
                    </div>
                    <div class="product__sidebar__comment__item__text">
                        <ul>
                            {% for tag in comment.post.tags.all %}
                                <li>{{ tag }}</li>
                            {% endfor %}
                        </ul>
                        <h5><a href="{{ comment.post.get_absolute_url }}">{{ comment.post.title }}</a></h5>
                        <span><i class="fa fa-eye"></i> {{ comment.post.views }}</span>
                        <hr>

                        <figure class="text-end">
                            <blockquote class="blockquote">
                                <p style="color: white">{{ comment.text|truncatewords:10 }}</p>
                            </blockquote>
                            <figcaption class="blockquote-footer">
                                Автор: <cite title="Source Title">{{ comment.name }}</cite>
                            </figcaption>
                        </figure>
                    </div>
                    <hr style="color: #e53637; height: 1px; background-color: #e53637">
                </div>
            {% endfor %}
        </div>
    </div>
</div>