metalnews3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),# Django JET URLS
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('news.urls', namespace='news'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('', MainPage.as_view(), name='post_list'),
    path('<str:slug>/', post_detail, name='post_detail'),
    path('album/<str:slug>/', AlbumDetailView.as_view(), name='album_detail'),
    path('album/review/<str:slug>/', AddReview.as_view(), name='add_review'),
    path('comment/<str:slug>/', AddComment.as_view(), name='add_comment'),
    path('category/<str:category_name>', CategoryListView.as_view(), name='category_post_list'),
    path('post/<int:pk>/like/',
         login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
         name='post_like'),
    path('post/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)),
         name='post_dislike'),
    path('comment/<int:pk>/like/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
         name='comment_like'),
    path('comment/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
         name='comment_dislike'),
    path('album/<int:pk>/like/',
         login_required(VotesView.as_view(model=Album, vote_type=LikeDislike.LIKE)),
         name='album_like'),
    path('album/<int:pk>/dislike/',
         login_required(VotesView.as_view(model=Album, vote_type=LikeDislike.DISLIKE)),
         name='album_dislike'),
]

news/forms.py
from django import forms

from news.models import Comment, Review


class CommentForm(forms.ModelForm):
    """Форма комментов"""

    class Meta:
        model = Comment
        fields = ('name', 'email', 'text')


class ReviewForm(forms.ModelForm):
    """Форма комментов"""

    class Meta:
        model = Review
        fields = ('text',)

news/views.py
import json

from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from django.contrib.contenttypes.models import ContentType
# Create your views here.
from news.models import Post, Category, Album, Comment, LikeDislike
from .forms import CommentForm, ReviewForm


class MainPage(ListView):
    model = Post
    template_name = 'news/post_list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        p = Paginator(Post.objects.select_related().all(), self.paginate_by)
        context['posts'] = p.page(context['page_obj'].number)
        context['categories'] = Category.objects.all()
        context['albums'] = Album.objects.all()
        context['comments'] = Comment.objects.all().order_by('-created')[:3]
        context['popular_day'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=1), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_week'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=7), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_month'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=30), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_years'] = Post.objects.all().annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        return context


class CategoryListView(ListView):
    model = Post
    template_name = 'news/category_post_list.html'
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        p = Paginator(Post.objects.select_related().filter(category__name=self.kwargs.get('category_name')), self.paginate_by)
        context['posts'] = p.page(context['page_obj'].number)
        context['comments'] = Comment.objects.all().order_by('-created')[:3]
        context['popular_day'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=1), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_week'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=7), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_month'] = Post.objects.all().filter(
            publish__range=[timezone.now() - timezone.timedelta(days=30), timezone.now()]).annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        context['popular_years'] = Post.objects.all().annotate(
            sum_views=Sum('views'), sum_votes=Sum('votes')).order_by('-sum_views', 'sum_votes')[:3]
        return context


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post.views += 1
    post.save(update_fields=['views'])
    context = {
        'post': post,
    }
    return render(request, 'news/post_detail.html', context)


class AddComment(View):
    """Комментарии"""

    def post(self, request, slug):
        form = CommentForm(request.POST)
        post = Post.objects.get(slug=slug)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.post = post
            form.save()
        return redirect(post.get_absolute_url())

class AddReview(View):
    """Отзыв"""

    def post(self, request, slug):
        form = ReviewForm(request.POST)
        album = Album.objects.get(slug=slug)
        user = request.user
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.album = album
            form.user = user
            form.save()
        return redirect(album.get_absolute_url())


class VotesView(View):
    model = None  # Модель данных - Статьи или Комментарии
    vote_type = None  # Тип комментария Like/Dislike

    def post(self, request, pk):
        obj = self.model.objects.get(pk=pk)
        # GenericForeignKey не поддерживает метод get_or_create
        try:
            likedislike = LikeDislike.objects.get(content_type=ContentType.objects.get_for_model(obj), object_id=obj.id,
                                                  user=request.user)
            if likedislike.vote is not self.vote_type:
                likedislike.vote = self.vote_type
                likedislike.save(update_fields=['vote'])
                result = True
            else:
                likedislike.delete()
                result = False
        except LikeDislike.DoesNotExist:
            obj.votes.create(user=request.user, vote=self.vote_type)
            result = True

        return HttpResponse(
            json.dumps({
                "result": result,
                "like_count": obj.votes.likes().count(),
                "dislike_count": obj.votes.dislikes().count(),
                "sum_rating": obj.votes.sum_rating()
            }),
            content_type="application/json"
        )

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'news/album_detail.html'
    context_object_name = 'album'

templates/news/album_detail.html
{% extends 'base.html' %}
{% load like_user_check %}
{% load static %}
{% block title %}
    {{ album.name }}
{% endblock %}
{% block content %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <a href="./categories.html">Categories</a>
                        <span>Romance</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Album Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg" data-setbg="{{ album.cover.url }}">
                            <div class="ep">{% if album.votes.sum_rating < 0 %}
                                <i class="fas fa-poop ">{% else %}
                                <i class="fas fa-fire-alt">{% endif %}</i> {{ album.votes.sum_rating }}
                            </div>
                            <div class="comment"><i class="fa fa-comments"></i> {{ album.review_set.count }}</div>

                        </div>

                    </div>

                    <div class="col-lg-9">
                        <div class="anime__details__text">
                            <div class="anime__details__title">
                                <h3>{{ album.name }}</h3>
                                <span>{{ album.band.name }}</span>
                            </div>
                            {#                            <div class="anime__details__rating">#}
                            {#                                <div class="rating">#}
                            {#                                    <a href="#"><i class="fa fa-star"></i></a>#}
                            {#                                    <a href="#"><i class="fa fa-star"></i></a>#}
                            {#                                    <a href="#"><i class="fa fa-star"></i></a>#}
                            {#                                    <a href="#"><i class="fa fa-star"></i></a>#}
                            {#                                    <a href="#"><i class="fa fa-star-half-o"></i></a>#}
                            {#                                </div>#}
                            {#                                <span>1.029 Votes</span>#}
                            {#                            </div>#}
                            <p>{{ album.description }}</p>
                            <div class="anime__details__widget">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Страна:</span> {{ album.band.country }}</li>
                                            <li><span>Группа:</span> {{ album.band.name }}</li>
                                            <li><span>Лейбл:</span> {{ album.label }}</li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Дата выхода:</span> {{ album.release_date }}</li>
                                            <li><span>Длительность:</span> {{ album.duration }}</li>
                                            <li><span>Жанры:</span>
                                                <ul>
                                                    <li>
                                                        {% for style in album.band.styles.all %}
                                                            {{ style }}{{ ' ' }}{% endfor %}
                                                    </li>
                                                </ul>
                                            </li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="blog__details__comment__item__text">
                                <div class="row">
                                    <div class="col-lg-3 mb-4">
                                        <h5>Оцени новость:</h5>
                                    </div>
                                    <div class="col-lg-4 mb-4">

                                        <a data-id="{{ album.id }}" data-type="album" data-action="like"
                                           {% if album.votes.likes.all|user_in:user %}style="background: #e53637"{% endif %}
                                           id="likecheck"><i
                                                class="fas fa-fire-alt"
                                                data-count="like">{{ album.votes.likes.count }}</i>
                                        </a>
                                        <a data-id="{{ album.id }}" data-type="album" data-action="dislike"
                                           {% if album.votes.dislikes.all|user_in:user %}style="background: #e53637"{% endif %}
                                           id="dislikecheck"><i
                                                class="fas fa-poop"
                                                data-count="dislike">{{ album.votes.dislikes.count }}</i>
                                        </a>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    {% if user.is_authenticated %}
                        <div class="anime__details__form">
                            <div class="section-title">
                                <h5>Оставь отзыв</h5>
                            </div>
                            <form action="{% url 'news:add_review' album.slug %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" id="contactparent" value="{{ user.id }}">
                                <textarea placeholder="Ваш отзыв" name="text"></textarea>
                                <button type="submit"><i class="fa fa-location-arrow"></i> Оставить отзыв</button>
                            </form>
                        </div>
                    {% else %}
                        Зарегайся, чорт!
                    {% endif %}
                    <div class="anime__details__review">
                        <div class="section-title">
                            <h5>Отзывы</h5>
                        </div>
                        {% for review in album.get_review %}
                            <div class="anime__review__item">
                                <div class="anime__review__item__pic">
                                    <img src="{% static 'img/blog/details/default_comment.png' %}" alt="">
                                </div>
                                <div class="anime__review__item__text">
                                    <h6>{{ review.user.username }}</h6>
                                    <p>{{ review.text }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="anime__details__sidebar">
                        <div class="section-title">
                            <h5>you might like...</h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-1.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Boruto: Naruto next generations</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-2.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">The Seven Deadly Sins: Wrath of the Gods</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-3.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Sword art online alicization war of underworld</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-4.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Fate/stay night: Heaven's Feel I. presage flower</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Anime Section End -->
{% endblock %}

templates/news/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load like_user_check %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="blog__details__title">
                        <h6>{% for tag in post.tags.all %}{{ tag }} {% endfor %}<span>- {{ post.publish }}</span></h6>
                        <h2>{{ post.title }}</h2>
                        <div class="blog__details__social">
                            <a href="#" class="facebook"><i class="fa fa-facebook-square"></i> Facebook</a>
                            <a href="#" class="pinterest"><i class="fa fa-pinterest"></i> Pinterest</a>
                            <a href="#" class="linkedin"><i class="fa fa-linkedin-square"></i> Linkedin</a>
                            <a href="#" class="twitter"><i class="fa fa-twitter-square"></i> Twitter</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ post.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__text">
                            <p>{{ post.content|safe }}</p>
                        </div>

                        <div class="blog__details__tags">
                            {% for tag in post.tags.all %}
                                <a href="{{ tag }}">{{ tag }}</a>
                            {% endfor %}
                        </div>
                        <div class="blog__details__comment__item__text">
                            <div class="row">
                                <div class="col-lg-3 mb-4">
                                    <h5>Оцени новость:</h5>
                                </div>
                                <div class="col-lg-4 mb-4">

                                    <a data-id="{{ post.id }}" data-type="post" data-action="like"
                                       {% if post.votes.likes.all|user_in:user %}style="background: #e53637"{% endif %}
                                       id="likecheck"><i
                                            class="fas fa-fire-alt"
                                            data-count="like">{{ post.votes.likes.count }}</i>
                                    </a>
                                    <a data-id="{{ post.id }}" data-type="post" data-action="dislike"
                                       {% if post.votes.dislikes.all|user_in:user %}style="background: #e53637"{% endif %}
                                       id="dislikecheck"><i
                                            class="fas fa-poop"
                                            data-count="dislike">{{ post.votes.dislikes.count }}</i>
                                    </a>
                                </div>

                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                {% if post.get_previous_by_created %}
                                    <div class="col-lg-6">
                                        <div class="blog__details__btns__item">
                                            <h5>
                                                <a href="{% url 'news:post_detail' post.get_previous_by_created.slug %}"><span
                                                        class="arrow_left"></span>
                                                    {{ post.get_previous_by_created.title }}</a>
                                            </h5>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if post.get_next_by_created %}
                                    <div class="col-lg-6">
                                        <div class="blog__details__btns__item next__btn">
                                            <h5>
                                                <a href="{% url 'news:post_detail' post.get_next_by_created.slug %}">{{ post.get_next_by_created.title }}
                                                    <span
                                                            class="arrow_right"></span></a></h5>
                                        </div>
                                    </div>
                                {% endif %}

                            </div>

                        </div>
                        <div class="blog__details__form" id="formComment">
                            <h4>Оставить коммент</h4>
                            <form action="{% url 'news:add_comment' post.slug %}"  method="post">
                                {% csrf_token %}
                                <input type="hidden" name="parent" id="contactparent" value="">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input type="text" placeholder="Имя" name="name" id="contactusername"
                                               required="">
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input type="text" placeholder="Email" name="email" id="contactemail"
                                               required="">
                                    </div>
                                    <div class="col-lg-12">
                                        <textarea placeholder="Сообщение" name="text" id="contactcomment"
                                                  required=""></textarea>
                                        <button type="submit" class="site-btn">Send Message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="blog__details__comment" id="comments">
                            <h4>{{ post.comment_set.count }} Комментов</h4>
                            {% for comment in post.get_comment %}
                                <div class="blog__details__comment__item">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="{% static 'img/blog/details/default_comment.png' %}" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>{{ comment.created }}</span>
                                        <h5>{{ comment.name }}</h5>

                                        <p>{{ comment.text }}</p>
                                        <a data-id="{{ comment.id }}" data-type="comment" data-action="like"
                                           {% if comment.votes.likes.all|user_in:user %}style="background: #e53637"{% endif %}
                                           id="likecheck"><i
                                                class="far fa-thumbs-up"
                                                data-count="like">{{ comment.votes.likes.count }}</i>
                                        </a>
                                        <a data-id="{{ comment.id }}" data-type="comment" data-action="dislike"
                                           {% if comment.votes.dislikes.all|user_in:user %}style="background: #e53637"{% endif %}
                                           id="dislikecheck"><i
                                                class="far fa-thumbs-down"
                                                data-count="dislike">{{ comment.votes.dislikes.count }}</i>
                                        </a>

                                        <a href="#formComment"
                                           onclick="addCommentReply('{{ comment.name }}', '{{ comment.id }}')">Ответить</a>

                                    </div>
                                </div>
                                {% for com_re in comment.comment_set.all %}
                                    <div class="blog__details__comment__item blog__details__comment__item--reply">
                                        <div class="blog__details__comment__item__pic">
                                            <img src="{% static 'img/blog/details/default_comment.png' %}" alt="">
                                        </div>
                                        <div class="blog__details__comment__item__text">
                                            <span>{{ com_re.created }}</span>
                                            <h5>{{ com_re.name }}</h5>
                                            <p>{{ com_re.text }}</p>
                                            <a data-id="{{ com_re.id }}" data-type="comment" data-action="like"
                                               {% if com_re.votes.likes.all|user_in:user %}style="background: #e53637"{% endif %}
                                               id="likecheck"><i
                                                    class="far fa-thumbs-up"
                                                    data-count="like"> {{ com_re.votes.likes.count }}</i>
                                            </a>
                                            <a data-id="{{ com_re.id }}" data-type="comment"
                                               data-action="dislike"
                                               {% if com_re.votes.dislikes.all|user_in:user %}style="background: #e53637"{% endif %}
                                               id="dislikecheck"><i
                                                    class="far fa-thumbs-down"
                                                    data-count="dislike"> {{ com_re.votes.dislikes.count }}</i>
                                            </a>
                                            <a href="#formComment"
                                               onclick="addCommentReply('{{ comment.name }}', '{{ comment.id }}')">Ответить</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->
    <script>
        function addCommentReply(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
    </script>
{% endblock %}